# ==== H2 PROFILI (garanti: RUN.bat bu profille calisir) ====
spring.datasource.url=jdbc:h2:mem:talepdb;DB_CLOSE_DELAY=-1
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=create-drop
spring.h2.console.enabled=true
spring.h2.console.path=/h2
